### ISSUE TITLE
CombineReducers uses rootState and seems to cause problem with other reducers (eg. reduceReducer)

### ISSUE THREAD

**Issue by tkreis** [redux-loop/redux-loop#178]
It seems like that the combineReducers uses the rootState instead of the passed in state while reducing: https://github.com/redux-loop/redux-loop/blob/master/src/combineReducers.js#L54 . 

At least in my case this seems to make the usage of reduceReducers very cumbersome. Since it always resets to the Root-state when something has changed in the innerReducer and loses the state set in the outerReducer the cycle before.

```
const outerReducer = ([state, cmd]) => {
    const [outerState, outerCmd] = otherReducer(state.outer, action);
    return [
      { ...state, app: outerState },
      Cmd.list([cmd, outerCmd]),
    ];
};

export default reduceReducers(
  combineReducers({
    inner: innerReducer,
   ...
  }),
 outerReducer,
);
```

By changing the line number [54](https://github.com/redux-loop/redux-loop/blob/master/src/combineReducers.js#L54) to state instead of rootState the tests still pass and it would fix the problem. Not sure if it would cause other problems tho.

EDIT: fix error wrongfully recursion in example.

**Comment by tkreis** [comment]
You're right my example is screwed up.  For now I've solved my issue by wrapping the combineReducer response in an other function which extends the return value with the state returned by reduceReducer. 
```
(loopReducer) => (state, action) => {
  const [innerState, innerCmd] = loopReducer(state, action);
  return [{ ...state, ...innerState }, innerCmd];
};
```

**Comment by bdwain** [comment]
FYI this is fixed as of 4.3.0

**Comment by g12i** [comment]
Hey @bdwain! The fix seem to broke my use case :). I was using 4.2 and I had to write my own `reduceReducers` implementation (it is almost identical to the official one but it flattens nested cmds).
```js

export function composeLoopReducers(...reducers) {
  return function(state, action) {
    let hasChanged = false;
    let cmds = [];

    const model = reducers.reduce((currState, reducer) => {
      let nextState = reducer(currState, action);

      if (isLoop(nextState)) {
        const cmd = getCmd(nextState);
        if (isListCmd(cmd)) {
          cmds.push(...cmd.cmds);
        } else {
          cmds.push(cmd);
        }
        nextState = getModel(nextState);
      }

      hasChanged = hasChanged || nextState !== currState;

      return nextState;
    }, state);

    return loop(hasChanged ? model : state, batchCmds(cmds));
  };
}
```
Now after the update following test start to fail:
```
it('creates a merged loop reducer which works with initial state and handle actions', () => {
    const rootInitialState = {
      foo: 5,
      bar: 10,
    };
    const DO_MATH = 'DO_MATH';
    const cmdA = Cmd.action({ type: 'A' });
    const cmdB = Cmd.action({ type: 'B' });

    const makeMultiplyReducer = initialState =>
      createReducer(initialState, {
        [DO_MATH]: (state, { payload }) => loop(state * payload, cmdA),
      });
    const makeSumReducer = initialState =>
      createReducer(initialState, {
        [DO_MATH]: (state, { payload }) => loop(state + payload, cmdB),
      });

    const rootReducer = combineLoopReducers({
      foo: composeLoopReducers(makeMultiplyReducer(rootInitialState.foo), makeSumReducer(rootInitialState.foo)),
      bar: composeLoopReducers(makeSumReducer(rootInitialState.bar), makeMultiplyReducer(rootInitialState.bar)),
    });

    const store = createStore(rootReducer, rootInitialState);
    store.dispatch({ type: DO_MATH, payload: 2 });
    const loopedState = store.getState();
    expect(getModel(loopedState)).to.be.deep.equal({
      foo: 12,
      bar: 24,
    });
    expect(getCmd(loopedState)).to.be.deep.equal(
      Cmd.list([Cmd.list([cmdA, cmdB]), Cmd.list([cmdB, cmdA])], { batch: true })
    );
  });
```
And the reason is that `getModel(loopedState)` returns a loop itself (because of the fix to this issue).

**Comment by bdwain** [comment]
Hm I've been able to pass the result of combineReducers to reduceReducers before. Why do you need to flatten nested Cmds? They should run fine without being flattened, and you're relying on internal details of Cmds that can change in a patch release.

**Comment by g12i** [comment]
Yeah you're right. But I'm still having a problem with a `reduceReducers` function. Let me open an issue for that.
